### PR TITLE
let cryo thermocouple work even if no sensor is detected

### PR DESCRIPTION
**Pull request by fazerlicourice7**
@benjamint8  try this.

### CODE REVIEW

**Comment by taitmate38** [comment]
Didn't work - will still hang if trying to start without a thermocouple amplifier. This time, it got stuck during the library initialization in `setup`

**Comment by fazerlicourice7** [comment]
`Serial.println("Error initializing cryo board at Addr 0x" + String(addrs[i], HEX));
          Serial.println("Continuing anyway. Will get garbage data.");`
Did you see these?

**Comment by fazerlicourice7** [comment]
@benjamint8 bump in case you forgot (not urgent)

**Comment by taitmate38** [comment]
this is not good to go, right? Still chasing down the memory leak/error

**Comment by fazerlicourice7** [comment]
Decided we don't need this since we introduced the config -> hardware versioning. Created an `E1_waterflow` version instead that didn't use the cryo thermocouples.

**Pull request closed without merging**
